# Generated by Django 3.1.6 on 2021-04-10 09:37

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(default=None, null=True, upload_to=books.models.book_upload_cover),
        ),
    ]
