# Generated by Django 3.1.6 on 2021-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_requestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'In Progress'), (20, 'Confirmed'), (30, 'Reject'), (40, 'Sent via mail Service'), (50, 'received Book'), (60, 'Sent Back'), (70, 'Received Back (Final)')]),
        ),
    ]
