# Generated by Django 3.1.6 on 2021-02-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210213_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
