# Generated by Django 3.1.6 on 2021-02-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.PositiveSmallIntegerField()),
                ('date_of_death', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('native_language', models.CharField(max_length=20)),
            ],
        ),
    ]
