# Generated by Django 3.1.6 on 2021-02-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210214_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(),
        ),
    ]
