# Generated by Django 3.1.6 on 2021-04-08 23:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.user_upload_avatar),
        ),
    ]
