# Generated by Django 3.1.6 on 2021-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('contact_to_email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1024)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
