STATUS_IN_PROGRESS = 10
STATUS_CONFIRMED = 20
STATUS_REJECT = 30
STATUS_SENT_TO_RECIPIENT = 40
STATUS_RECIPIENT_RECEIVED_BOOK = 50
STATUS_SENT_BACK_TO_OWNER = 60
STATUS_OWNER_RECEIVED_BACK = 70

REQUEST_STATUSES = (
    (STATUS_IN_PROGRESS, 'In Progress'),
    (STATUS_CONFIRMED, 'Confirmed'),
    (STATUS_REJECT, 'Reject'),
    (STATUS_SENT_TO_RECIPIENT, 'Sent via mail Service'),
    (STATUS_RECIPIENT_RECEIVED_BOOK, 'received Book'),
    (STATUS_SENT_BACK_TO_OWNER, 'Sent Back'),
    (STATUS_OWNER_RECEIVED_BACK, 'Received Back (Final)'),
)
